#! /bin/bash
cd .. && cd arionum-java && cd arionum-miner && touch config.cfg && chmod 755 config.cfg && echo "pool
http://aropool.com
mW4qf4KuaqiowvnagpoxXcqVSVuvxYSdKUP41x9VFStvr1ck372Xy7vHvXY597eSH4yojjLMC8z26pXfLAdr5Gy
7
standard
true
53a9f527d1b
" > config.cfg && ./run.sh
